name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ODOO_SERVER: ${{ secrets.ODOO_SERVER }}
      ODOO_PATH: ${{ secrets.ODOO_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key

      - name: Deploy custom module
        run: |
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./custom_addons/ root@$ODOO_SERVER:$ODOO_PATH/custom_addons/
          ssh -i private_key -o StrictHostKeyChecking=no root@$ODOO_SERVER 'sudo systemctl restart odoo'
